version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
#      - monitoring
      - koda_sidekick_koda_network
    volumes:
      - grafana_data:/var/lib/grafana
      - ./graphana/provisioning:/etc/grafana/provisioning/
    environment:
      GF_SECURITY_ADMIN_PASSWORD: your_admin_password_here
      GF_USERS_ALLOW_SIGN_UP: false
#      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_ANONYMOUS_ENABLED: true
#      GF_AUTH_ANONYMOUS_ORG_NAME: Main Org
#      GF_AUTH_ANONYMOUS_ORG_ROLE: Viewer
#      GF_INSTALL_PLUGINS: grafana-simple-json-datasource
#      GF_DATASOURCES: >
#        {
#          "apiVersion": 1,
#          "datasources": [
#            {
#              "name": "Prometheus",
#              "type": "prometheus",
#              "access": "proxy",
#              "url": "http://prometheus:9090",
#              "isDefault": true
#            }
#          ]
#        }

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - koda_sidekick_koda_network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
#      - ./prometheus/prometheus_data:/prometheus
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

  docker-exporter:
    image: prom/container-exporter:latest
    ports:
      - "9104:9104"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - koda_sidekick_koda_network

networks:
  koda_sidekick_koda_network:
    external: true

volumes:
  grafana_data:
  prometheus_data:

