{
 "title": "Koda Sidekick",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Koda Sidekick is up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"sidekick_api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidekick: latest failed attempt to connect to Gradio/LLava",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gradio_llava_connectivity_status{gradio_llava_connectivity_status=\"failed-to-connect\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Koda Sidekick connected to Gradio/LLava",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gradio_llava_connectivity_status{gradio_llava_connectivity_status=\"connected\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}